name: encodable
description: Utility functions allowing any class to be encoded to JSON and to set its fields from a map
dependencies:
  tuple:
    path: ../tuple
  zip:
    path: ../zip
dev_dependencies:
  unittest: any
